name: Python CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install coverage flake8

      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest test.py
          coverage report -m

      - name: Run flake8 lint check
        run: |
          flake8 kuratowski.py --max-line-length=120 || true  # avoid failing entire workflow

      - name: Upload coverage report (optional)
        if: success()
        run: |
          coverage html
          echo "You can view coverage in the htmlcov/index.html file"
